CREATE TABLE mydb.products
(
  ID          BIGINT          NOT NULL AUTO_INCREMENT,
  POINT_ID    BIGINT,
  PRICE       BIGINT,
  AMOUNT      BIGINT       NOT NULL,
  NAME        VARCHAR(45)  NULL,
  DESCRIPTION VARCHAR(255) NULL,
  FOREIGN KEY (POINT_ID) REFERENCES points (ID),
  PRIMARY KEY (ID)
);

INSERT INTO mydb.products (POINT_ID, PRICE, AMOUNT, NAME , DESCRIPTION) VALUES (?,?,?,?,?);

ALTER TABLE mydb.products MODIFY PRICE DOUBLE ;

ALTER TABLE mydb.products MODIFY AMOUNT DOUBLE ;