CREATE TABLE mydb.products (
  ID INT NOT NULL AUTO_INCREMENT,
  POINT_ID BIGINT,
  PRICE BIGINT,
  AMOUNT BIGINT NOT NULL,
  NAME VARCHAR(45) NULL,
  DESCRIPTION VARCHAR (255) NULL ,
  FOREIGN KEY (POINT_ID) REFERENCES points(ID),
  PRIMARY KEY (ID));

ALTER TABLE mydb.products ADD ID_MARKET int;

INSERT INTO mydb.products (NAME) values ('name');

SELECT * FROM mydb.products where ID = 1;